#!/bin/sh

export XDG_CURRENT_DESKTOP=dwl
export XDG_SESSION_DESKTOP=dwl
export XDG_SESSION_TYPE=wayland

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
	exec dbus-run-session "$0" "$@"
fi

exec sh -c '
	slstatus -s | dwl -s "swaybg -i /home/user1/Pictures/wallpapers/fantasy.png <&- &" "$@"
' sh "$@"
